# you might want to change this
source-strip-prefixes := /afs/cs.stanford.edu/u/mhn/test/cbiexp/jpeg/src/

report-series := inverse-100

# you might want to change this
training-runs := 200

name := jpeg
experiment := ..
schemes := all branches returns scalar-pairs

include ../../src/analysis-rules.mk
